Server:
  RunMode: debug
  HttpPort: 8080
  ReadTime: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileExt: .log
Database:
  DBType: mysql
  UserName: root
  Password: 123456
  Host: localhost:3306
  DBName: as
  TablePrefix: ""
  Charset: utf8mb4
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30